#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Apr 16 12:22:13 MDT 2025
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 93706be23f9043bc938ea838d9cd1da5 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot top_level_tb_behav xil_defaultlib.top_level_tb -log elaborate.log"
xelab -wto 93706be23f9043bc938ea838d9cd1da5 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot top_level_tb_behav xil_defaultlib.top_level_tb -log elaborate.log

